[package]
name = "kdtree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
plotlib = "0.5.1"
rayon = "1.6.1"
atomic_float = "0.1.0"
csv = "1.1"
